apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: snmpd
  labels:
    tier: monitoring
    app: snmpd
    version: v1
spec:
  template:
    metadata:
      labels:
        name: snmpd
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          image: quay.io/gaker/docker-snmpd:latest
          name: snmpd
          volumeMounts:
            - name: host_proc
              mountPath: /host_proc
              readOnly: true
      volumes:
        - name: host_proc
          hostPath:
              path: /proc
